### ISSUE TITLE
Errors in the console

### ISSUE THREAD

**Issue by galexandre** [LiffeyValleyAC/LiffeyValleyAC.github.io#287]
Hi all, 
I noticed a couple of errors being displayed in the console when accessing the home page.
I have a fix on the way and I aim to deploy it later today.
The fix consists of an update of the list of scripts being loaded for the main page and an update of a URL to reach https instead of http.
![lvac-errors](https://user-images.githubusercontent.com/3588802/148641897-a5af65f4-459d-4745-b3fc-bd822adaccad.png)

**Comment by paulbalfe** [comment]
Hi Geoffrey can you also create a link on the home page to myrun TBM 2022 results page please?

**Comment by galexandre** [comment]
Hi @paulbalfe 
I think this is out of scope of the error. The best would be to create another issue with the requirements (what/where/how/when). 
Unfortunately, I will not have much time this evening and tomorrow to look at that. However, you are admin as well, which allow you to push to the master branch.

**Comment by galexandre** [comment]
Part of the issue is now gone.
