### ISSUE TITLE
Displaying the Winter League PDF File

### ISSUE THREAD

**Issue by paulbalfe** [LiffeyValleyAC/LiffeyValleyAC.github.io#301]
The LVAC-Final-Winter-League-2021-22.pdf file is uploaded to the repository. Is there a way to link to the pdf file and display, such as https://liffeyvalleyac.com/winterleague/2022/Final.pdf

**Comment by galexandre** [comment]
Looking at it now

**Comment by galexandre** [comment]
Specific page created, https://liffeyvalleyac.com/winterleague/, there is a link in the page to access the results. Moreover, the pdf has been moved to the asset directory.

**Comment by paulbalfe** [comment]
Thanks @galexandre
